### ISSUE TITLE
大佬，咨询下，这个工具只能存一页数据吗

### ISSUE THREAD

**Issue by lucsus** [W01fh4cker/hunter-to-excel#1]
大佬，咨询下，这个工具只能存一页数据吗？输入页数3，就只存第三页数据吗？

**Comment by W01fh4cker** [comment]
是的，这是hunter官方接口规定的，参考https://hunter.qianxin.com/home/helpCenter?r=5-1-2，但是可以自己控制每页资产条数。

**Comment by W01fh4cker** [comment]
是的，这是hunter官方接口规定的，参考https://hunter.qianxin.com/home/helpCenter?r=5-1-2
但是可以自己控制每页资产条数。
